---
title: "4 panel plot"
output: html_notebook
---

#setup
```{r}
library(tidyverse)
library(tweedie)
library(lme4)
library(vegan)
library(gdrive)
library(mvobservr) # devtools::install_github("noaa-afsc/mvobservr")

batch <- 1  # 1 or 2
output_name <- paste0("output_data/param_plot_batch", batch, ".Rdata")
```



```{r simulation_setup}
# Constants

# Set how many populations per scenario to generate
n_samples_per_level <- 50
# Set bias levels for species (change on observed trips; 0 = no bias, -0.25 = 25% reduction)
bias <- c(0, -0.25)
# Set target Berger-Parker index (dominance) levels.
bp_level <- 0.6
# Set number of permutations
n_permutations <- 1000

# Defaults for varying params
# Set the Tweedie power parameter (lambda). 1 < p < 2 is typical for biomass.
tweedie_power <- 1.6
# Set the dispersion parameter for the Tweedie distribution.
# Higher values create more variance (further from target BP).
phi <- 3
# Set the desired total biomass for every saved population.
fixed_total_biomass <- 6 #log scale
# Set the number of trips 
ntrips <- 500
# Set target coverage rate
trip_coverage <- 0.25
# Set the mu scalar
mu_scalar <- 100

```


```{r}
# Set up varying parameters and their levels
params_to_test <- data.frame(
  param = c("tweedie_power", "phi", "fixed_total_biomass", "ntrips", "trip_coverage", "mu_scalar"),
  param_display_name = c("Tweedie power parameter (poisson-gamma)",
                         "Tweedie phi parameter (dispersion)",
                         "Total Biomass (log scale)",
                         "Total trips",
                         paste0("Number of observed trips (out of ",ntrips," total)"),
                         "Tweedie mu parameter (mean)"
  ),
  param_values = c("1.1, 1.3, 1.5, 1.7, 1.9", #power
                   "1, 3, 5, 7, 9", #phi
                   "3, 4, 5, 6, 7", #log total biomass
                   "50, 100, 250, 500, 1000", #total trips
                   "0.1, 0.3, 0.5, 0.7, 0.9", #coverage rate
                   "1, 10, 100, 1000, 2000" #mu scalar
  ),
  defaults = c(tweedie_power, phi, fixed_total_biomass, ntrips, trip_coverage, mu_scalar)
)
```


```{r}
param_values_df <- params_to_test %>% 
  select(param, param_values) %>%
  separate_wider_delim(
    cols = param_values, 
    delim = ",", 
    names = c("val1", "val2", "val3", "val4", "val5")
  ) %>%
  pivot_longer(cols=starts_with("val"), values_to = "param_val") %>%
  mutate(param_val = as.numeric(param_val)) %>%
  select(-name)
```


```{r generatedata}
# for reproducibility
if(batch == 1) {
  set.seed(123)
} else if (batch == 2) {
  set.seed(456)
} else stop("'batch' needs to be either 1 or 2!")

trip_sets_adj <- map(rep(1:nrow(param_values_df), n_samples_per_level), ~{
  #replace the variable parameter with the loop value, all other values remain t default
  assign(param_values_df$param[.x], param_values_df$param_val[.x])
  #print(paste(bp_level, ntrips, tweedie_power, mu_scalar, phi, fixed_total_biomass, trip_coverage))
  
  #set up data frame for trips
  catches <- data.frame(uid = 1:ntrips)

  #create catches
  catches$sp_1 <- rtweedie(ntrips, p = tweedie_power, mu = mu_scalar*bp_level, phi = phi)
  catches$sp_2 <- rtweedie(ntrips, p = tweedie_power, mu = 100*(1-bp_level), phi = phi)

  #standardize catches
  catches <- catches %>%
    mutate(total_biomass = sum(sp_1 + sp_2)) %>%
    mutate(scalar = (10^fixed_total_biomass)/total_biomass) %>% #fixed_total_biomass on log scale
    mutate(across(c(sp_1, sp_2), function(x) x*scalar)) %>%
    select(-scalar, -total_biomass) %>%
    mutate(biomass_total = sp_1 + sp_2) %>%
    mutate(bp_level = bp_level,
           bp_true = sum(sp_1)/sum(biomass_total),
           ntrips = ntrips,
           tweedie_power = tweedie_power,
           mu_scalar = mu_scalar,
           phi = phi,
           fixed_total_biomass = fixed_total_biomass,
           trip_coverage = trip_coverage) %>%
    mutate(param_mod = param_values_df$param[.x],
           param_value = param_values_df$param_val[.x],
           .before=1)

  #select observed and add bias
  catches <- catches %>%
    mutate(obs = rbinom(nrow(.), 1, trip_coverage)) %>%
    mutate(sp_1 = ifelse(obs == 1, sp_1 * (1+bias[1]), sp_1),
         sp_2 = ifelse(obs == 1, sp_2 * (1+bias[2]), sp_2),
         biomass_total = sp_1 + sp_2
         )

  return(catches)
}, .progress=TRUE)


```


##permanova
```{r}
adon_formula = "Y~factor(obs)"

res_p <- map(trip_sets_adj, ~{
  Y <- .x %>% dplyr::select(starts_with("sp_"))
  adon <- vegan::adonis2(as.formula(adon_formula), data = .x, permutations = n_permutations, method="euclidean")
  data.frame(metric = "biomass_total", perma_p = adon$`Pr(>F)`[1])
}, .progress=TRUE) #1 min for 60 sets
res_p <- list_rbind(res_p, names_to = "set")
```


##mvglm
  60 sets x 100 perm  = 30 min on laptop using 12 cores = 0.50m/s = 0.00500m/s/p
  60 sets x 200 perm  = 45 min on laptop using 12 cores = 0.75m/s = 0.00375m/s/p
  10 sets x 1000 perm = 17 min                          = 1.70m/s = 0.00170m/s/p
```{r}
res_m <- imap(1:length(trip_sets_adj), ~{
  print(paste0("***set ", .x, " ", now()))
  trip_sets_adj[[.x]] %>%
      mutate(observed = ifelse(obs==1, 'Y', 'N')) %>%
      pivot_longer(cols=starts_with("sp_"),
                   names_to = 'species', values_to = 'biomass') %>%
      mvglm_obs(block = NULL, add_var = NULL, n_permutations= n_permutations, nCores = 12) %>%
      pluck("results") %>%
      {data.frame(t(c(uni.p = .$uni.p, biomass_total = .$p)))} %>%
      pivot_longer(everything(), names_to = "metric", values_to = "mvglm_p") 
})
res_m <- list_rbind(res_m, names_to = "set") %>%
  filter(metric == "biomass_total")
```


#combine output
```{r}
res_comb <- map(trip_sets_adj, ~ .x[1, c("param_mod", "param_value")]) %>%
  list_rbind(names_to = "set") %>%
  left_join(res_p, by="set") %>%
  left_join(res_m, by=c("set","metric"))
res_comb


save(res_comb, file = output_name)
```



#upload files to gdrive
  only once when transferring from data ran on cloud workstation
```{r}
mvobservr_dribble <- gdrive_set_dribble(folder_id = "1xQTE9ap6GBnz4ErSrULbEqvPUtQzpHt_")
gdrive_upload(local_path = output_name, gdrive_dribble = mvobservr_dribble)
```





#pull down and load data files from gdrive
```{r}
load(gdrive_download(local_path = "output_data/param_plot_batch1.Rdata", gdrive_dribble = mvobservr_dribble))
res_comb_tbl <- res_comb
load(gdrive_download(local_path = "output_data/param_plot_batch2.Rdata", gdrive_dribble = mvobservr_dribble))
res_comb <- res_comb |> mutate(set = set + max(res_comb_tbl$set))
res_comb_tbl <- rbind(res_comb_tbl, res_comb)
rm(res_comb)
```

#make plot
```{r, fig.height=6}
res_comb_tbl %>%
  pivot_longer(cols=c(perma_p, mvglm_p), names_to = "test", values_to = "p") %>%
  group_by(param_mod, param_value, test) %>%
  summarize(psig = mean(p<=0.05), .groups="drop") %>%
  inner_join(params_to_test, by=c("param_mod" = "param")) %>%
  mutate(test = factor(test, levels = c("mvglm_p","perma_p"),
                       labels = c("MVGLM", "permanova")
                       )
  ) %>%
  mutate(param_value = case_when(
                         param_mod == "trip_coverage" ~ param_value*ntrips, #convert to number of trips
                         TRUE ~ param_value
                       )
  ) %>%
  mutate(defaults = case_when(
                         param_mod == "trip_coverage" ~ defaults*ntrips, #convert to number of trips
                         TRUE ~ defaults
                       )
  ) %>%
  ggplot(aes(x=param_value, y=psig, col=test, group=test)) +
  geom_line() +
  geom_point() +
  facet_wrap(~param_display_name, scales="free_x",ncol=2) +
  theme_bw() +
  labs(x=NULL, y="proportion of simulations with significant results",
       title = "Power vs. simulation parameters",
       subtitle = paste0(n_samples_per_level * 2, " replicates per value")
       ) +
  geom_vline(aes(xintercept=defaults), linetype='dashed')
```








