---
title: "delta vs dominance"
output: html_notebook
---

The goal is to see how detection rates differ for fisheries that are dominated by a single species vs. ones that are more even.

Simulation:
  2 species
  generate weights with varying levels of biomass allocated to species 1 (dominant)
  from mvglm, get delta between overall p-value and the p-value of the dominant species
  
```{r setup}
library(tidyverse)
library(FMAtools)  
library(mvobservr)
source("functions/mvglm_obs_dd.R")
source("functions/loop_mvglm.R")
```


```{r}
trips = 300
prop_targ = 0.3
sp1_params = c(3, 0.1)
sp2_params = c(log(exp(sp1_params[1])*(1-prop_targ)), 0.1*(1-prop_targ))

tripdat <- data.frame(uid = 1:trips) %>%
  mutate(sp1 = rlnorm(trips, sp1_params),
         sp2 = rlnorm(trips, sp2_params))

prop_sp1 <- sum(tripdat$sp1)/(sum(tripdat$sp1) + sum(tripdat$sp2)); prop_sp1

pdat <- tripdat %>%
  mutate(observed = 'N', BLOCK = 'block', days.fished = 1) 

loop_mvglm(pdat, covrate = 0.25, nperm = 10, bias = 0)
```

```{r}
twospp_dat_by_prop <- function(ntrips, prop, params) {
  #draw a weight from a lognormal distribution (specified by params) for each of ntrips
  #set species 1 weight (sp1) as the drawn weight times the proportion of species 1 (prop)
  #set species 2 weight (sp2) as the remainder
  #drop the total weight
  data.frame(uid = 1:ntrips) %>%
    mutate(wt = rlnorm(ntrips, params),
           sp1 = wt*prop,
           sp2 = wt*(1-prop)) %>%
    select(-wt)
}

twospp_dat_by_params <- function(ntrips, params1, params2) {
  data.frame(uid = 1:ntrips) %>%
    mutate(sp1 = rlnorm(trips, sp1_params),
         sp2 = rlnorm(trips, sp2_params)
    )
}

```


```{r, warning=FALSE, message=FALSE, eval=FALSE}
nperm = 30 #about 1 minute for 100 permutations for 3 species
nrep = 1
props = seq(0.5, 0.95, by=0.25)

length(props)*nrep*nperm/100/60 #estimated run hours at 1 min/100 perm
biasrate = -0.1
ntrips = 300

params = c(3, 1) #lognormal mu and sd

res_prop_b30 <- map(rep(props, each=nrep), ~{
  print(now())
  twospp_dat_by_prop(ntrips, .x, params) %>%
    mutate(BLOCK = "block", days.fished = 1) %>% #needed for mvglm_obs_dd
    loop_mvglm(covrate = 0.25, nperm = nperm, bias = biasrate) %>%
    pluck("ps") %>% #just care about p-values for this one
    mutate(prop = .x)
  })



res_prop_b30 <- map(rep(props, each=nrep), ~{
  print(now())
  d <- twospp_dat_by_params(ntrips, sp1_params, sp2_params)
  prop <- sum(d$sp1)/(sum(d$sp1)+sum(d$sp2))
  twospp_dat_by_prop(ntrips, .x, params) %>%
    mutate(BLOCK = "block", days.fished = 1) %>% #needed for mvglm_obs_dd
    loop_mvglm(covrate = 0.25, nperm = nperm, bias = biasrate) %>%
    pluck("ps") %>% #just care about p-values for this one
    mutate(prop = .x)
  })


res_prop_b30_df <- list_rbind(res_prop_b30) 

res_prop_b30_df %>%
  count(prop)

save(res_prop_b30_df, file="output_data/simdat2spp100rep100perm_propramp_b20_20250820.Rdat")

```

```{r}
res_prop_b30_df %>%
  mutate(delta = p - sp1) %>%
  ggplot(aes(x=prop, y=delta)) +
  geom_point()
```

