---
title: "Untitled"
output: html_document
date: "2025-09-22"
---


```{r}
load("source_data/1_mvglm_obs_data_segmented.Rdata") #original data

model_start <- merge(sums_l, spp_exp_segmented %>% filter(segment_new == "Keep") %>%
                       select(STRATA, Species) %>% distinct()) %>%
  select(species = Species, uid = TRIP_ID, days.fished, observed = OBSERVED_FLAG, biomass = Biomass, BLOCK, days.fished, STRATA)

model_start.l <- split(model_start, f = ~ STRATA)

spp_top_n <- model_start.l$`OB FIXED BSAI` %>%
  group_by(species) %>%
  summarize(b=sum(biomass)) %>%
  arrange(desc(b)) %>%
  slice_max(n=2, order_by=b)

#extract a single stratum and reduce the number of species
x <- model_start.l$`OB FIXED BSAI` %>%
  filter(species %in% spp_top_n$species)  
```

#run original package code (for comparison)
```{r}
set.seed(123)

spp_top_n <- model_start.l$`OB FIXED BSAI` %>%
  group_by(species) %>%
  summarize(b=sum(biomass)) %>%
  arrange(desc(b)) %>%
  slice_max(n=2, order_by=b)

#extract a single stratum and reduce the number of species
x <- model_start.l$`OB FIXED BSAI`%>%
  filter(species %in% spp_top_n$species)  

out_orig <- mvglm_obs(x, 
                          add_var = "days.fished",
                          block = "BLOCK",
                          n_permutations = 100,
                          )
out_orig$results

xi <- x %>%
  mutate(biomass = ifelse(observed == "Y", biomass*0.5, biomass))

out_adj <- mvglm_obs(xi, 
                          add_var = "days.fished",
                          block = "BLOCK",
                          n_permutations = 100,
                          )
out_adj$results #0.00990099 with days.fished, same without

trips <- xi %>%
  pivot_wider(names_from = species, values_from = biomass)

 #permanova, one value for all species vs. obs factor
  Y <- trips %>% dplyr::select(`Pacific Cod`, `Sablefish (blackcod)`)
  adon <- vegan::adonis2(Y ~ factor(observed) + BLOCK + days.fished, data = trips, permutations = 500, method="euclidean")
  adon #0.001996 with block + days fished, same with just days, same without either
  
  
oeres <- trips %>%
  rename(sp_1 = `Pacific Cod`, sp_2 = `Sablefish (blackcod)`) %>%
  mutate(obs = as.numeric(ifelse(observed == "Y", "1", "0"))) %>%
  mutate(vessnum = BLOCK) %>%
  mutate(biomass_total = sp_1 + sp_2) %>%
  ObserverEffectStats(metrics = c("sp_1","sp_2","biomass_total"), nperm_mvglm = nperm, nboot_triplet = nboot, nperm_adon=nboot)

oeres %>%
  select(metric, mean_O, mean_U, tp, bhatt, Fp, AICd, bhate, KSp, median_diff, bhatm, mvglm_p, perma_p)
```



```{r}
b <- seq(-0.5, 0.5, by=0.1)
rres <- map(b, ~{
  xi <- x %>%
    mutate(biomass = ifelse(observed == "Y", biomass*(1-.x), biomass))
  
  out_adj <- mvglm_obs(xi, 
                          add_var = "days.fished",
                          block = "BLOCK",
                          n_permutations = 500,
                          )
  trips <- xi %>%
  pivot_wider(names_from = species, values_from = biomass)

  oeres <- trips %>%
    rename(sp_1 = `Pacific Cod`, sp_2 = `Sablefish (blackcod)`) %>%
    mutate(obs = as.numeric(ifelse(observed == "Y", "1", "0"))) %>%
    mutate(vessnum = BLOCK) %>%
    mutate(biomass_total = sp_1 + sp_2) %>%
    ObserverEffectStats(metrics = c("sp_1","sp_2","biomass_total"), nperm_mvglm = 500, nboot_triplet = 500, nperm_adon=500)

  list(out_adj$results, oeres)
}) 

save(rres, file="output_data/OB_FIXED_BSAI_biasramp_20251203.Rdat")

rres_oe <- lapply(rres, `[[`, 2)
names(rres_oe) <- as.character(b)
rres_oe <- rres_oe %>%
  list_rbind(names_to = "b")


rres_mv <- lapply(rres, `[[`, 1)
rres_mv<- lapply(rres_mv, `[[`, 'p')


rres_oe %>%
  select(b, metric, mvglm_p, perma_p, tp) %>%
  filter(metric == "biomass_total") %>%
  arrange(as.numeric(b)) %>%
  add_column(mp = unlist(rres_mv)) %>%
  pivot_longer(cols= c('mvglm_p','perma_p', 'tp' ,'mp')) %>%
  ggplot(aes(x=as.numeric(b), y=value, col=name)) +
  geom_point() +
  geom_line() +
  labs(x="bias",y="p-value", title = "OB FIXED BSAI, top 2 species", 
    subtitle = 'keeping original obs, not using block or days fished, bias on all species') +
  geom_hline(yintercept = 0.05, linetype='dashed')


rres_oe %>%
  select(b, metric, sum_O, sum_U) %>%
  pivot_wider(names_from = metric, values_from = c(sum_O, sum_U)) %>%
  # mutate(bp_O = sum_O_sp_1/sum_O_biomass_total,
  #        bp_U = sum_U_sp_1/sum_U_biomass_total,
  #        bp = (sum_O_sp_1 + sum_U_sp_1) / (sum_O_biomass_total + sum_U_biomass_total)
  # )
  mutate(b1 = sum_O_sp_1 / sum(x$biomass[x$species=="Pacific Cod" & x$observed=="Y"]),
         b2 = sum_O_sp_2 / sum(x$biomass[x$species=="Sablefish (blackcod)" & x$observed=="Y"]))


```

```{r}
rres2 <- map(b, ~{
  xi <- x %>%
    mutate(biomass = ifelse(observed == "Y", biomass*(1-.x), biomass))
  
  out_adj <- mvglm_obs(xi, 
                          add_var = "days.fished",
                          block = "BLOCK",
                          n_permutations = 500,
                          )
  trips <- xi %>%
  pivot_wider(names_from = species, values_from = biomass)

  oeres <- trips %>%
    rename(sp_1 = `Pacific Cod`, sp_2 = `Sablefish (blackcod)`) %>%
    mutate(obs = as.numeric(ifelse(observed == "Y", "1", "0"))) %>%
    mutate(vessnum = BLOCK) %>%
    mutate(biomass_total = sp_1 + sp_2) %>%
    ObserverEffectStats(metrics = c("sp_1","sp_2","biomass_total"), nperm_mvglm = 100, nboot_triplet = 500, nperm_adon=500, mv_block = "BLOCK", mv_addvar = "days.fished")

  list(out_adj$results, oeres)
}) 

rres2_oe <- lapply(rres2, `[[`, 2)
names(rres2_oe) <- as.character(b)
rres2_oe <- rres2_oe %>%
  list_rbind(names_to = "b")


rres2_mv <- lapply(rres2, `[[`, 1)
rres2_mv<- lapply(rres2_mv, `[[`, 'p')


rres2_oe %>%
  select(b, metric, mvglm_p, perma_p, tp) %>%
  filter(metric == "biomass_total") %>%
  add_column(mp = unlist(rres2_mv))%>%
  pivot_longer(cols= c('mvglm_p','perma_p', 'tp', 'mp')) %>%
  ggplot(aes(x=as.numeric(b), y=value, col=name)) +
  geom_point() +
  geom_line() +
  labs(x="bias",y="p-value", title = "OB FIXED BSAI, top 2 species", 
    subtitle = 'keeping original obs, using both block and days fished, bias on all species') +
  geom_hline(yintercept = 0.05, linetype='dashed')


trips <- x %>%
  pivot_wider(names_from = species, values_from = biomass) %>%
    rename(sp_1 = `Pacific Cod`, sp_2 = `Sablefish (blackcod)`) %>%
    mutate(obs = as.numeric(ifelse(observed == "Y", "1", "0"))) %>%
    mutate(vessnum = BLOCK) %>%
    mutate(biomass_total = sp_1 + sp_2) #%>%
    #mutate(BLOCK = as.character(rbinom(nrow(.), 1, 0.5)))

 Y <- trips %>% dplyr::select(starts_with("sp_"))

  vegan::adonis2(as.formula(Y~factor(obs)), data = trips, permutations = 500, method="euclidean")
  vegan::adonis2(as.formula(Y~factor(obs)), data = trips, permutations = 500, method="euclidean", strata = BLOCK)
  vegan::adonis2(as.formula(Y~factor(obs)+BLOCK), data = trips, permutations = 500, method="euclidean")
  vegan::adonis2(as.formula(Y~factor(obs)+days.fished), data = trips, permutations = 500, method="euclidean")
  vegan::adonis2(as.formula(Y~factor(obs)+BLOCK+days.fished), data = trips, permutations = 500, method="euclidean")
```



```{r}
rres_oe %>%
  left_join(rres2_oe, by=c("b","metric"), suffix=c("","2")) %>%
  select(b, metric, mvglm_p, perma_p, tp, mvglm_p2, perma_p2) %>%
  filter(metric == "biomass_total") %>%
  arrange(as.numeric(b)) %>%
  pivot_longer(cols= c('mvglm_p','perma_p', 'tp', 'mvglm_p2','perma_p2')) %>%
  ggplot(aes(x=as.numeric(b), y=value, col=name)) +
  geom_point() +
  geom_line() +
  labs(x="bias",y="p-value", title = "OB FIXED BSAI, top 2 species", 
    subtitle = 'keeping original obs, bias on both species, p = no block or days, p2 = block + days') +
  geom_hline(yintercept = 0.05, linetype='dashed')

```


